format = """
[â•­â”€userâ”€â”€â”€â¯](27) $username$fill$time$cmd_duration
[â•°â”€projectâ¯](bold 202) $directory$git_branch$git_status$fill$python
$character\ 
"""

[character]
success_symbol = "[âœ](bold green)"
error_symbol = "[âœ—](bold red)"


[cmd_duration]
format = "[took $duration]($style)"
min_time = 4
show_milliseconds = false
disabled = false
style = "bold italic 207"


[fill]
symbol = "  => -> --> >= <= === /= ~> >-> <-< <> |> "
style = "103"


[username]
show_always = true
disabled = false
style_user = "99"
format = '[$user]($style) '


[os]
disabled = true # Disabled by default


[directory]
read_only = "ğŸ”’"
format = '[$path]($style)[$read_only]($read_only_style) '
style = "bold 204"


[directory.substitutions]
"Documents" = "ğŸ“„ "
"Music" = "ğŸµ "
"Pictures" = "ğŸ–¼ï¸ "


[git_branch]
symbol = 'ğŸŒ± '


[git_status]
conflicted = 'ğŸ³'
ahead = 'ğŸğŸ’¨'
behind = 'ğŸ˜°'
diverged = 'ğŸ˜µ'
up_to_date = 'âœ“'
untracked = 'ğŸ¤·'
stashed = 'ğŸ“¦'
modified = 'ğŸ“'
staged = '[++\($count\)](green)'
renamed = 'ğŸ‘…'
deleted = 'ğŸ—‘'


[python]
symbol = "ğŸ "
python_binary = "py"
style = "207 bold"
format = '[ ${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)'
version_format = '$major.${minor}'


[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "171"
format = "[ at $time ]($style)"
